# Generated by Django 4.1.4 on 2022-12-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=15, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Resultados',
                'verbose_name_plural': 'Resultados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=13, verbose_name='Teléfono')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('poblacion', models.CharField(max_length=50, verbose_name='Población')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('resultado', models.ForeignKey(default='Abierto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='llamadas.resultados', verbose_name='resultado')),
            ],
        ),
    ]
